# Generated by Django 4.2 on 2023-05-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=256)),
                ('Customer_Sex', models.IntegerField(choices=[(1, '男'), (0, '女')])),
                ('Customer_Age', models.IntegerField(default=0)),
                ('Customer_Tel', models.IntegerField(blank=True, null=True)),
                ('Customer_Type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Order_Time', models.DateTimeField(auto_now_add=True)),
                ('Order_Destination', models.CharField(max_length=256)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=256)),
                ('Product_Type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('WareHouse_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('WareHouse_Name', models.CharField(max_length=256)),
                ('WareHouse_Address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Vehicle_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=256, null=True)),
                ('WareHouse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('ProductBatch_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductBatch_Current_Inventory', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ProductBatch_Production_Time', models.DateTimeField(blank=True, null=True)),
                ('ProductBatch_Production_Place', models.CharField(max_length=256)),
                ('ProductBatch_Expiration_Time', models.DateTimeField(blank=True, null=True)),
                ('ProductBatch_Warehousing_Time', models.DateTimeField(blank=True, null=True)),
                ('ProductBatch_Supply_Time', models.DateTimeField(blank=True, null=True)),
                ('ProductBatch_Supply_Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ProductBatch_Supply_Address', models.CharField(max_length=256)),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.product')),
                ('Supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.supplier')),
                ('WareHouse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('OrderDetail_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('SalePrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.order')),
                ('Product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.product')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('Dispatcher_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dispatcher_Name', models.CharField(max_length=256)),
                ('Dispatcher_Sex', models.IntegerField(choices=[(1, '男'), (0, '女')])),
                ('Dispatcher_Age', models.IntegerField(default=0)),
                ('Dispatcher_Tel', models.IntegerField(blank=True, null=True)),
                ('WareHouse_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('Delivery_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Latest_Delivery_Time', models.DateField()),
                ('Current_Status', models.IntegerField(choices=[(0, '即将配送'), (1, '正在配送中'), (2, '已送达')], default=0)),
                ('Current_Position', models.CharField(max_length=256)),
                ('Completion_Time', models.DateTimeField(blank=True, null=True)),
                ('Dispatcher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.dispatcher')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.order')),
                ('Vehicle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewSet.vehicle')),
            ],
        ),
    ]
