# Generated by Django 4.2 on 2023-05-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_Tel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dispatcher',
            name='Dispatcher_Tel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
