# Generated by Django 4.2 on 2023-05-27 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSet', '0002_alter_customer_customer_tel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='Product_ID',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='ProductBatch_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ViewSet.productbatch'),
            preserve_default=False,
        ),
    ]
