# Generated by Django 4.2 on 2023-05-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewSet', '0003_remove_orderdetail_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='Latest_Delivery_Time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
